import Footer from "@/components/Footer.tsx";
import Nav from "@/components/Nav.tsx";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import Providers from "./providers.tsx";
import { ProfileProvider } from "@/context/ProfileContext.tsx";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ahmad Elmesery - Motion Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <ProfileProvider>
            <Nav />
            <main>{children}</main>
            <Footer />
          </ProfileProvider>
        </Providers>
      </body>
    </html>
  );
}
