import Footer from "@/components/Footer.tsx";
import Nav from "@/components/Nav.tsx";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import Providers from "./providers.tsx";
import ScrollTop from "@/components/ScrollTop.tsx";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ahmad Elmesery - Motion Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={font.className}>
        <Providers>
          <Nav />
          <main>{children}</main>
          <ScrollTop />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
